#!/usr/bin/env zsh

setopt extendedglob

for f ($0:A:h/^install) rm -rf ~/.$f:t && ln -sfv $f ~/.$f:t
git -C $0:A:h submodule update -j 20 --init --remote --depth=1

for k in user.name user.email; do
  if ! git config -f ~/.gitidentity $k > /dev/null; then
    read "v?${(%):-%4FEnter default $k for git: %f}"
    if [[ -n $v ]] git config -f ~/.gitidentity $k $v
  fi
done

if [[ $OSTYPE == darwin* ]] && ! infocmp -x tmux-256color &> /dev/null; then
  tic -xo ~/.terminfo =(echo "nsterm,\n use=xterm-256color,\n\ntmux-256color,
      E3=\E[3J,TS=\E]0;,U8#1,dim=\E[2m,dsl=\E]0;\007,fsl=^G,indn=\E[%p1%dS,ncv@,
      hpa=\E[%i%p1%dG,hs,invis=\E[8m,kbs=^?,ritm=\E[23m,rmso=\E[27m,rmxx=\E[29m,
      sgr=\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p5%t;2%;%?%p7
      %t;8%;m%?%p9%t\016%e\017%;,sitm=\E[3m,smso=\E[7m,smxx=\E[9m,tsl=\E]0;,
      vpa=\E[%i%p1%dd,use=xterm+edit,use=xterm+pcfkeys,use=xterm+tmux,
      use=screen-256color,\n\nxterm+tmux,\n Cr=\E]112\007,Cs=\E]12;%p1%s\007,
      Ms=\E]52;%p1%s;%p2%s\007,Se=\E[2 q,Ss=\E[%p1%d q,\n\nxterm-256color,\n XT,
      E3=\E[3J,dim=\E[2m,kbs=^?,oc=\E]104\007,ritm=\E[23m,sitm=\E[3m,smxx=\E[9m,
      rmxx=\E[29m,rmcup=\E[?1049l\E[23;0;0t,rs1=\Ec\E]104\007,sgr=%?%p9%t\E(0%e
      \E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?
      %p7%t;8%;m,smcup=\E[?1049h\E[22;0;0t,u8=\E[?%[;0123456789]c,
      use=xterm+tmux,use=xterm+256color,use=xterm-new,")
fi
